package hr.tvz.experimate.experimate.push;

import hr.tvz.experimate.experimate.domain.user.User;
import jakarta.persistence.*;

import java.time.LocalDateTime;

/**
 * Represents a browser's Web Push subscription for a specific user and device.
 *
 * <p>A single user can hold multiple active subscriptions — one per browser/device.
 * The {@code endpoint} is globally unique: it is the push service URL generated by
 * the browser and is the natural identifier for "this browser on this device".
 *
 * <p>{@code p256dh} and {@code auth} are browser-generated encryption keys required
 * to encrypt the notification payload before sending it to the push service.
 */
@Entity
@Table(name = "push_subscription")
public class PushSubscription {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    @ManyToOne
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    @Column(nullable = false, length = 2048)
    private String endpoint;

    @Column(nullable = false, length = 512)
    private String p256dh;

    @Column(nullable = false, length = 512)
    private String auth;

    private LocalDateTime createdAt;

    // For Hibernate
    protected PushSubscription() {}

    public PushSubscription(User user, String endpoint, String p256dh, String auth) {
        this.user = validateUser(user);
        this.endpoint = validateNotBlank(endpoint, "endpoint");
        this.p256dh = validateNotBlank(p256dh, "p256dh");
        this.auth = validateNotBlank(auth, "auth");
        this.createdAt = LocalDateTime.now();
    }

    public Integer getId() { return id; }

    public User getUser() { return user; }

    public String getEndpoint() { return endpoint; }

    public String getP256dh() { return p256dh; }

    public String getAuth() { return auth; }

    public LocalDateTime getCreatedAt() { return createdAt; }

    private User validateUser(User user) {
        if (user == null) throw new IllegalArgumentException("User cannot be null");
        return user;
    }

    private String validateNotBlank(String value, String field) {
        if (value == null || value.isBlank())
            throw new IllegalArgumentException(field + " cannot be blank");
        return value;
    }
}
