-- Recurring, auto-renewing subscription that keeps a partner_pin highlighted on the map.
-- One subscription per pin (UNIQUE partner_pin_id). The "highlighted" state shown to clients
-- is derived from status + current_period_end at read time, not stored here.
-- A daily scheduler charges the next period and advances the window, or expires the row
-- when a pending cancellation reaches current_period_end.
CREATE TABLE IF NOT EXISTS partner_pin_subscription (
    id                   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    partner_pin_id       integer NOT NULL,
    status               character varying(20) NOT NULL,
    current_period_start timestamp(6) without time zone NOT NULL,
    current_period_end   timestamp(6) without time zone NOT NULL,
    cancel_at_period_end boolean NOT NULL DEFAULT false,
    created_at           timestamp(6) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE ONLY partner_pin_subscription
    ADD CONSTRAINT fk_partner_pin_subscription_pin FOREIGN KEY (partner_pin_id) REFERENCES partner_pin(id) ON DELETE CASCADE;

ALTER TABLE ONLY partner_pin_subscription
    ADD CONSTRAINT uq_partner_pin_subscription_pin UNIQUE (partner_pin_id);
