CREATE TABLE IF NOT EXISTS app_user (
    id                            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name                    character varying(255),
    last_name                     character varying(255),
    date_of_birth                 date,
    id_number                     character varying(255),
    bio                           character varying(255),
    onboarding_completed          boolean DEFAULT false,
    password                      character varying(255),
    personality_agreeableness     double precision,
    personality_computed_at       timestamp(6) without time zone,
    personality_conscientiousness double precision,
    personality_extraversion      double precision,
    personality_neuroticism       double precision,
    personality_openness          double precision,
    profile_photo_filename        character varying(255),
    quiz_completion_count         integer DEFAULT 0,
    rating                        double precision NOT NULL,
    username                      character varying(255)
);

CREATE TABLE IF NOT EXISTS tour_listing (
    id               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city             character varying(255),
    latitude         double precision,
    longitude        double precision,
    meeting_date     timestamp(6) without time zone,
    post_date        timestamp(6) without time zone,
    reserved         boolean NOT NULL,
    tour_description text,
    host_id          integer
);

CREATE TABLE IF NOT EXISTS booking_request (
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_date timestamp(6) without time zone,
    status       character varying(255),
    guest_id     integer,
    listing_id   integer,
    CONSTRAINT booking_request_status_check CHECK ((status::text = ANY ((ARRAY['PENDING'::character varying, 'ACCEPTED'::character varying, 'DECLINED'::character varying])::text[])))
);

CREATE TABLE IF NOT EXISTS quiz_result (
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    completed_at timestamp(6) without time zone,
    created_at   timestamp(6) without time zone,
    status       character varying(20),
    user_id      integer UNIQUE,
    CONSTRAINT quiz_result_status_check CHECK ((status::text = ANY (ARRAY['AWAITING'::text, 'COMPLETED'::text, 'CANCELLED'::text])))
);

CREATE TABLE IF NOT EXISTS quiz_result_answers (
    quiz_result_id integer NOT NULL,
    answer_value   integer,
    item_number    integer NOT NULL,
    PRIMARY KEY (quiz_result_id, item_number)
);

CREATE TABLE IF NOT EXISTS rating (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_posted timestamp(6) without time zone,
    review      character varying(255),
    score       integer,
    rated_id    integer,
    rater_id    integer
);

CREATE TABLE IF NOT EXISTS refresh_token (
    id                   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expiration_date_time timestamp(6) without time zone,
    token                character varying(255),
    user_id              integer UNIQUE
);

CREATE TABLE IF NOT EXISTS tour_reservation (
    id                       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cancelled_timestamp      timestamp(6) without time zone,
    completed_timestamp      timestamp(6) without time zone,
    date_of_reservation      timestamp(6) without time zone,
    end_timestamp            timestamp(6) without time zone,
    guest_check_in_timestamp timestamp(6) without time zone,
    guest_checked_in         boolean,
    guest_rated              boolean,
    host_check_in_timestamp  timestamp(6) without time zone,
    host_checked_in          boolean,
    host_rated               boolean,
    start_timestamp          timestamp(6) without time zone,
    status                   character varying(20),
    ended_by_user_id         integer,
    guest_id                 integer,
    listing_id               integer,
    CONSTRAINT tour_reservation_status_check CHECK ((status::text = ANY (ARRAY['CONFIRMED'::text, 'ACTIVE'::text, 'COMPLETED'::text, 'CLOSED'::text, 'CANCELLED'::text, 'EXPIRED'::text])))
);

ALTER TABLE ONLY booking_request
    ADD CONSTRAINT fk_booking_request_guest FOREIGN KEY (guest_id) REFERENCES app_user(id);

ALTER TABLE ONLY booking_request
    ADD CONSTRAINT fk_booking_request_listing FOREIGN KEY (listing_id) REFERENCES tour_listing(id);

ALTER TABLE ONLY quiz_result
    ADD CONSTRAINT fk_quiz_result_user FOREIGN KEY (user_id) REFERENCES app_user(id);

ALTER TABLE ONLY quiz_result_answers
    ADD CONSTRAINT fk_quiz_result_answers FOREIGN KEY (quiz_result_id) REFERENCES quiz_result(id);

ALTER TABLE ONLY rating
    ADD CONSTRAINT fk_rating_rated FOREIGN KEY (rated_id) REFERENCES app_user(id);

ALTER TABLE ONLY rating
    ADD CONSTRAINT fk_rating_rater FOREIGN KEY (rater_id) REFERENCES app_user(id);

ALTER TABLE ONLY refresh_token
    ADD CONSTRAINT fk_refresh_token_user FOREIGN KEY (user_id) REFERENCES app_user(id);

ALTER TABLE ONLY tour_listing
    ADD CONSTRAINT fk_tour_listing_host FOREIGN KEY (host_id) REFERENCES app_user(id);

ALTER TABLE ONLY tour_reservation
    ADD CONSTRAINT fk_tour_reservation_ended_by FOREIGN KEY (ended_by_user_id) REFERENCES app_user(id);

ALTER TABLE ONLY tour_reservation
    ADD CONSTRAINT fk_tour_reservation_guest FOREIGN KEY (guest_id) REFERENCES app_user(id);

ALTER TABLE ONLY tour_reservation
    ADD CONSTRAINT fk_tour_reservation_listing FOREIGN KEY (listing_id) REFERENCES tour_listing(id);
