-- Add authorization role to every user account; existing rows default to 'USER'.
ALTER TABLE app_user
    ADD COLUMN role VARCHAR(20) NOT NULL DEFAULT 'USER';

-- Stores business-specific data for users who have been granted PARTNER role.
-- Linked 1:1 to app_user; deleted automatically when the user is removed.
CREATE TABLE IF NOT EXISTS partner_profile (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name  character varying(255) NOT NULL,
    contact_email character varying(255) NOT NULL,
    website       character varying(255),
    created_at    timestamp(6) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    user_id       integer NOT NULL
);

ALTER TABLE ONLY partner_profile
    ADD CONSTRAINT partner_profile_user_id_unique UNIQUE (user_id);

ALTER TABLE ONLY partner_profile
    ADD CONSTRAINT fk_partner_profile_user FOREIGN KEY (user_id) REFERENCES app_user(id) ON DELETE CASCADE;
