-- Permanent venue locations that partners place on the map.
-- Each pin belongs to one partner_profile and may have an optional logo image.
CREATE TABLE IF NOT EXISTS partner_pin (
    id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    partner_profile_id  integer NOT NULL,
    name                character varying(255) NOT NULL,
    description         text,
    logo_filename       character varying(255),
    latitude            double precision NOT NULL,
    longitude           double precision NOT NULL,
    active              boolean NOT NULL DEFAULT true,
    created_at          timestamp(6) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE ONLY partner_pin
    ADD CONSTRAINT fk_partner_pin_profile FOREIGN KEY (partner_profile_id) REFERENCES partner_profile(id) ON DELETE CASCADE;

-- Time-bound events attached to a partner pin.
-- Visible to all authenticated users as soon as they are created.
CREATE TABLE IF NOT EXISTS partner_event (
    id                integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    partner_pin_id    integer NOT NULL,
    title             character varying(255) NOT NULL,
    description       text,
    ticket_vendor_url character varying(2048),
    start_datetime    timestamp(6) without time zone NOT NULL,
    end_datetime      timestamp(6) without time zone NOT NULL,
    created_at        timestamp(6) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE ONLY partner_event
    ADD CONSTRAINT fk_partner_event_pin FOREIGN KEY (partner_pin_id) REFERENCES partner_pin(id) ON DELETE CASCADE;

-- Feed advertisements interleaved with TourListing cards.
-- active_from / active_until are nullable; null means no scheduling boundary on that side.
-- view_count is a stub (always 0) reserved for future impression tracking.
CREATE TABLE IF NOT EXISTS promoted_ad (
    id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    partner_profile_id  integer NOT NULL,
    title               character varying(255) NOT NULL,
    description         text,
    image_filename      character varying(255),
    link_url            character varying(2048),
    active              boolean NOT NULL DEFAULT true,
    view_count          integer NOT NULL DEFAULT 0,
    active_from         timestamp(6) without time zone,
    active_until        timestamp(6) without time zone,
    created_at          timestamp(6) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE ONLY promoted_ad
    ADD CONSTRAINT fk_promoted_ad_profile FOREIGN KEY (partner_profile_id) REFERENCES partner_profile(id) ON DELETE CASCADE;
