-- Stores Web Push subscriptions, one row per browser/device per user.
-- The same user can have multiple active subscriptions (e.g. laptop + phone).
-- p256dh and auth are the browser-generated encryption keys included in the
-- PushSubscription object; the backend needs them to encrypt each payload.
CREATE TABLE IF NOT EXISTS push_subscription (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     integer NOT NULL,
    endpoint    VARCHAR(2048) NOT NULL,
    p256dh      VARCHAR(512)  NOT NULL,
    auth        VARCHAR(512)  NOT NULL,
    created_at  timestamp(6) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_push_subscription_endpoint UNIQUE (endpoint)
);

ALTER TABLE ONLY push_subscription
    ADD CONSTRAINT fk_push_subscription_user FOREIGN KEY (user_id) REFERENCES app_user(id) ON DELETE CASCADE;
